#!/usr/bin/env python3
"""Count documents"""

from pymongo import MongoClient


if __name__ == "__main__":
    client = MongoClient('mongodb://127.0.0.1:27017')
    my_db = client.my_db
    school_collection = my_db.school
    count = school_collection.count_documents({})
    print(count)

