#!/usr/bin/env python3
"""Update documents"""

from pymongo import MongoClient


if __name__ == "__main__":
    client = MongoClient('mongodb://127.0.0.1:27017')
    my_db = client.my_db
    school_collection = my_db.school
    update_query = {"name": "Holberton school"}
    update_data = {"$set": {"address": "972 Mission street"}}
    result = school_collection.update_many(update_query, update_data)
    print("Modified documents:", result.modified_count)

